### PR TITLE
Add coverage for OUTLETS INP section

### PR DESCRIPTION
**Pull request by aerispaha**
Adds coverage for the [OUTLETS] INP section. Now we can get a dataframe of the OUTLETS section in models with `model.inp.outlets`. The higher level API now also include outlets in the `model.links` accessor. 

Partially addresses #57

### CODE REVIEW

**Comment by bemcdonnell** [comment]
@aerispaha achhoooooooAnyUnitTests ?

**Comment by aerispaha** [comment]
@bemcdonnell heck yeah. I've added a [doctest](https://github.com/pyswmm/swmmio/pull/229/files#diff-8b81f02dc27445b6c704ae266ed23b2ea48d51d571fc9ccdd386be67ecbbb92dR1696-R1706) for `inp.outlets`, so we get a little bit of docs and a test (two rocks with one bird)

**Review by bemcdonnell — APPROVED** [review]

**Comment by aerispaha** [comment]
this is @bemcdonnell right now
image

**Comment by bemcdonnell** [comment]
@aerispaha my beard isn't as gray as yours!!

**Pull request merged**
