### PR TITLE
Update spatial.py

### PR DESCRIPTION
**Pull request by chuwenhao123**
fixed that written polygon shapefile may be not correctly loaded in ArcGIS

### CODE REVIEW

**Comment by bemcdonnell** [comment]
#202

**Comment by bemcdonnell** [comment]
@chuwenhao123 can you please make a quick commit and bump down the Pillow version number required so we can get this to pass?

**Comment by chuwenhao123** [comment]
Hello @bemcdonnell, I observed that you may not have direct control over the Pillow version, as shown in the image below. On my own computer, I utilized the swmmio.draw_model function with Pillow version 9.5, and it worked perfectly. "I plan to attempt committing a compatible version at a later time.
image
image

**Comment by chuwenhao123** [comment]
Hi @bemcdonnell, I've managed to control the PILLOW version in the requirements.txt file. I hope this resolves the issue.
image

**Comment by bemcdonnell** [comment]
@karosc, nice work on SWMM-toolkit. I retriggered the build (from the beach 🏖️) and things are looking good.  We obviously need to circle back to see if we need to deprecate pillow or move to v10.

**Review by bemcdonnell — APPROVED** [review]
@aerispaha pending your approval.  Take it away :)

**Review by aerispaha — APPROVED** [review]
Looks good! Approving this from my paternity leave 👶

**Pull request merged**
